# Generated by Django 4.2.3 on 2023-08-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tiendaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=32, null=True)),
                ('provincia', models.CharField(blank=True, max_length=32, null=True)),
                ('region', models.CharField(blank=True, max_length=32, null=True)),
                ('fechaCreacion', models.CharField(blank=True, max_length=32, null=True)),
                ('telefonoContacto', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=32, null=True)),
                ('codigo', models.CharField(blank=True, max_length=32, null=True)),
                ('precioVenta', models.CharField(blank=True, max_length=32, null=True)),
                ('cantidad', models.CharField(blank=True, max_length=32, null=True)),
                ('tiendaRelacionada', models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendas.tiendainfo')),
            ],
        ),
    ]
