# Generated by Django 4.2.3 on 2023-08-04 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_alter_productoinfo_tiendarelacionada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoinfo',
            name='tiendaRelacionada',
            field=models.ForeignKey(blank=True, max_length=32, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendas.tiendainfo'),
        ),
    ]
